# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Resigning IPA File"
  lane :resign_ipa do

    setup_ci

    sync_code_signing(  
      type: "appstore",
      readonly: is_ci
    )

    # match(
    # git_basic_authorization: Base64.strict_encode64("Raamasaamy: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"),
    # type: "appstore", readonly: true
    # )

    setup_ci

    resign(
      ipa: "./submitted_test.ipa",
      signing_identity: "iPhone Distribution: Robert Bosch GmbH (JRH3BDU5ZX)",
      provisioning_profile: {
        "com.bosch.prod.remotefiresafety" => "./profile/comboschprodremotefiresafety_AppStore.mobileprovision",
        "com.bosch.prod.remotefiresafety.NotificationService" => "./profile/comboschprodremotefiresafetyNotificationService_AppStore.mobileprovision"
      },
      entitlements: {
        "com.bosch.prod.remotefiresafety" => "./entitlements/entitlements.plist",
        "com.bosch.prod.remotefiresafety.NotificationService" => "./entitlements/NotificationEntitlements.plist"
      },
    )

    # pilot( api_key_path: "fastlane/AuthKey.json" )
  end
end