name: Copy Specific Files to Another Repo

on:
  push:
    branches:
      - main  # Trigger only when main is updated

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone destination repository
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@github.com/Raamasaamy/TestPipe.git destination-repo

      - name: Copy specific files to destination repo
        run: |
          cp submitted_test.ipa destination-repo/
          cp entitlements.plist destination-repo/entitlements/
          
          cd destination-repo
          git add .
          git commit -m "Copied specific files from source repo"
          git push origin main
