name: Trigger Workflow in Other Repo

# on:
  # push:
    # branches:
      # - main  # Trigger on pushes to main branch

on:
  workflow_dispatch: # Allows you to trigger the workflow manually

jobs:
  call-workflow-passing-data:
    uses: Raamasaamy/TestPipe/.github/workflows/CodeSign.yml@main


