name: Trigger Workflow in Other Repo

# on:
  # push:
    # branches:
      # - main  # Trigger on pushes to main branch

on:
  workflow_dispatch: # Allows you to trigger the workflow manually

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-assets
          path: ./assets # directory containing multiple files, binary fie and entitlement.plist
          retention-days: 1
          
      - name: Trigger Workflow in TestPipe Repository
        run: |
          REPO_OWNER="Raamasaamy"
          REPO_NAME="TestPipe"
          WORKFLOW_ID="CodeSign.yml"  # Filename of workflow in repo B
          GITHUB_TOKEN="${{ secrets.TARGET_REPO_PAT }}"  # Store token in A's secrets

          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{
              "ref": "main",
              "inputs": {
                "ipa_path": "'"./Remote.ipa"'",
                "certificate_name": "'"iPhone Distribution: Robert Bosch GmbH (JRH3BDU5ZX)"'",
                "new_bundle_id": "'"com.bosch.prod.remotefiresafety"'",
                "entitlements_plist_path": "'"./entitlements/entitlements.plist"'",
                "main_app_provisioning_profile_path": "'""'",
                "output_ipa_path": "'"./output.ipa"'",
                "extension_bundle_id_suffix": "'".NotificationService"'",
                "extension_entitlements_plist_dir": "'"/entitlements"'",
                "extension_provisioning_profile_dir": "'""'"
              }
            }' \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_ID/dispatches"

