name: Trigger Workflow in Other Repo

# on:
  # push:
    # branches:
      # - main  # Trigger on pushes to main branch

on:
  workflow_dispatch: # Allows you to trigger the workflow manually

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Repository B
        run: |
          REPO_OWNER="owner_of_repo_b"
          REPO_NAME="repo_b_name"
          WORKFLOW_ID="workflow_b.yml"  # Filename of workflow in repo B
          GITHUB_TOKEN="${{ secrets.REPO_B_TRIGGER_TOKEN }}"  # Store token in A's secrets
          INPUT_ENVIRONMENT="staging"
          INPUT_VERSION="1.2.3"

          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{
              "ref": "main",
              "inputs": {
                "environment": "'"$INPUT_ENVIRONMENT"'",
                "version": "'"$INPUT_VERSION"'"
              }
            }' \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_ID/dispatches"
